# Generated by Django 3.0.4 on 2020-03-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_concerts_headliner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerts',
            name='headliner',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
