<<<<<<< HEAD
# Generated by Django 2.2.11 on 2020-03-29 20:36
=======
# Generated by Django 3.0.4 on 2020-03-29 20:36
>>>>>>> 0693ff8238e78b11c9a0edde6828ec5af8d484a7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_concerts_headliner'),
    ]

    operations = [
<<<<<<< HEAD
        migrations.AddField(
            model_name='concerts',
            name='imageURL',
            field=models.CharField(default='N/A', max_length=500),
        ),
=======
>>>>>>> 0693ff8238e78b11c9a0edde6828ec5af8d484a7
        migrations.AlterField(
            model_name='concerts',
            name='headliner',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
