# Generated by Django 3.0.4 on 2020-03-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20200330_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='upcomingConcerts',
        ),
    ]
