# Generated by Django 3.0.4 on 2020-03-30 02:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_remove_venue_upcomingconcerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='upcomingConcerts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=215), blank=True, default=['NO UPCOMING CONCERTS!'], size=80),
            preserve_default=False,
        ),
    ]
